services:
  music-discovery-app:
    container_name: "${CONTAINER_NAME:-music-discovery-app-container}"
    image: "${params.DOCKER_IMAGE}"
    build:
      context: ${REACT_BUILD_PATH}
    ports:
      - "8563:8563"
    command: ["npm", "run", "dev"]
    restart: always
    stdin_open: true
    tty: true

  playwright-tests:
    container_name: playwright-music-discovery-app-container
    build: .
    depends_on:
      - music-discovery-app  # Waits for music-discovery-apps to start
    environment:
      - BASE_URL="http://react-app:8563"
    command: ["npx", "playwright", "test"]
