services:
  react-app:
    container_name: "${CONTAINER_NAME:-music-discovery-app-container}"
    build:
      context: ${REACT_BUILD_PATH}
    ports:
      - "8563:8563"
    volumes:
      - ../music-discovery-webpage:/app/Music-Discovery-Web-page
      - /app/Music-Discovery-Web-page/node_modules
    command: ["npm", "run", "dev"]
    restart: always
    stdin_open: true
    tty: true

  playwright-tests:
    container_name: playwright-music-discovery-app-container
    build: .
    depends_on:
      - react-app  # Waits for React app to start
    environment:
      - BASE_URL="http://react-app:8563"
    command: ["npx", "playwright", "test"]
